### ISSUE TITLE
Visualize resutls

### ISSUE THREAD

**Issue by marcomiglionico94** [EryiXie/PlaneRecNet#1]
Hi, I was able to run the network and get the depth map. I wanted to know how to do you visualize the 3D reconstruction of the picture like you show in the paper? Do you convert the depth + original image into a point cloud and then visualize it? Or do you use any other technique?

**Comment by EryiXie** [comment]
Hi, I convert the depth + RGB into a point cloud to visualize it (with open3d), just like you said. Therefore,  the camera intrinsic matrix is needed.

**Comment by AIMads** [comment]
Hey do you have the possibility to share this script?
