### ISSUE TITLE
Feature tensors with different shapes.

### ISSUE THREAD

**Issue by cnu1439** [EryiXie/PlaneRecNet#6]
Hi, 
    thanks for the code. When i was testing with pre-trained models with test image I'm getting following error. Attaching test image.
Thanks.

(prn_test) dev@linux:/workspace/planerecnet$ python3 simple_inference.py --config=PlaneRecNet_101_config --trained_model=weights/PlaneRecNet_101_9_125000.pth  --image=test.jpg:/workspace/test.jpg
Inference image: test.jpg
torch.Size([425, 640, 3])
test.jpg
/home/dev/miniconda/envs/prn_test/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272204863/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
torch.Size([1, 128, 107, 160])
torch.Size([1, 128, 108, 160])
Traceback (most recent call last):
  File "/workspace/planerecnet/simple_inference.py", line 357, in <module>
    inference_image(net, inp, out, depth_mode=args.depth_mode)
  File "/workspace/planerecnet/simple_inference.py", line 154, in inference_image
    results = net(batch)
  File "/home/dev/miniconda/envs/prn_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/planerecnet/planerecnet.py", line 93, in forward
    mask_pred = self.mask_head(mask_features)
  File "/home/dev/miniconda/envs/prn_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/planerecnet/planerecnet.py", line 494, in forward
    feature_add_all_level += self.convs_all_levels[i](mask_feat)
RuntimeError: The size of tensor a (107) must match the size of tensor b (108) at non-singleton dimension 2

![test](https://user-images.githubusercontent.com/5406199/148641255-bb448f23-61e2-417d-9385-00a447807877.jpg)

**Comment by wangyusenofficial** [comment]
I think this due to the Unet structure, the input img size must be guaranteed to be divided by 2^n (n is the number of unet layers).

**Comment by cnu1439** [comment]
yeah. got it. working now. thanks for the reply.

**Comment by EryiXie** [comment]
To be more accurate, the image height and width should be evenly divided by 32.
